# Generated by Django 2.2.3 on 2019-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(height_field=models.IntegerField(), upload_to='images', width_field=models.IntegerField()),
        ),
    ]
