# Generated by Django 2.2.3 on 2019-07-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0003_auto_20190707_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='height',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='width',
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
