# Generated by Django 2.2.3 on 2019-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0005_auto_20190707_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='height',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='width',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
