# Generated by Django 2.2.3 on 2019-07-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0006_auto_20190707_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='height',
            field=models.IntegerField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='width',
            field=models.IntegerField(auto_created=True),
        ),
    ]
