# Generated by Django 2.2.3 on 2019-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0008_auto_20190707_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, height_field='height', upload_to='images', width_field='width'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='title',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
