# Generated by Django 2.2.3 on 2019-07-19 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0010_auto_20190708_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 19, 44, 25, 653529)),
        ),
    ]
