# Generated by Django 2.2.3 on 2019-07-21 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0011_auto_20190719_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
