# Generated by Django 2.2.3 on 2019-07-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_board', '0015_auto_20190722_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='favorite',
            new_name='favorites',
        ),
    ]
